[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["Abin Simon <abinsimon10@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version="0.15", features=["extra-traits"] }
quote = "0.6"
